/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ysahn' at '6/19/16 9:45 PM' with Gradle 2.14
 *
 * @author ysahn, @date 6/19/16 9:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
